---
- name: Configuration changes
  become: true
  hosts: logicservers
  tasks:

    - name: "install nginx"
      debug:
        msg: "Install nginx on: {{ inventory_hostname }}"

    - name: "Upgrade nginx"
      debug:
        msg: "Upgrade nginx on: {{ inventory_hostname }}"

    - name: "Configure nginx"
      debug:
        msg: "Start nginx on: {{ inventory_hostname }}"
      notify: restart nginx
      changed_when: True

    - name: "Verify nginx"
      debug:
        msg: "Verify: {{ inventory_hostname }}"

  handlers:
    - name: restart nginx
      debug:
        msg: "CALLED HANDLER FOR RESTART"
